on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DB_HOST }}
          username: ${{ secrets.DB_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Creating project folder if it doesn't exist"
            mkdir -p /home/ubuntu/nest_dars
            cd /home/ubuntu/nest_dars

            if [ ! -d .git ]; then
              echo "Cloning repository"
              git clone https://github.com/Ozodbek-cloud/Server.git .
            else
              echo "Pulling latest changes"
              git pull origin main
            fi

            echo "Stopping containers"
            sudo /usr/bin/docker compose down

            echo "Building containers"
            sudo /usr/bin/docker compose build

            echo "Running containers"
            sudo /usr/bin/docker compose up -d
